cluster.name: "elasticsearch"
node.name: "node-1"
network.host: 0.0.0.0
network.publish_host: localhost1
path.repo: ["/usr/share/elasticsearch/backup"]
discovery.seed_hosts:
  - localhost1
  - localhost2
  - localhost3
cluster.initial_master_nodes:
  - node-1
  - node-2
  - node-3
node.master: true
node.data: true

xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true