version: '3.4'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - "ELASTICSEARCH_USERNAME=elastic"
      - "ELASTICSEARCH_PASSWORD=toast1ng1234"
    ports:
      - 5601:5601
    networks:
      - elasticsearch_efk

networks:
  elasticsearch_efk:
    external:
      name: elasticsearch_efk
