version: '3.4'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - "ELASTICSEARCH_USERNAME=elastic"
      - "ELASTICSEARCH_PASSWORD=1234"
    ports:
      - 5601:5601
    networks:
      - efk
    depends_on:
      - elasticsearch

networks:
  efk:
    driver: bridge
